<a href="https://colab.research.google.com/github/Disha5199/Python-Practice-Question/blob/main/python_%3F_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1) Reverse a string without using built-in methods.
s = "hello"
rev = ""
for i in s:
    rev = i + rev
print("Reversed:", rev)



Reversed: olleh


In [ ]:
#Q2) Check if a string is a palindrome.
s = "madam"
rev = ""
for i in s:
    rev = i + rev

if s == rev:
    print("is Palindrome")
else:
    print("is Not Palindrome")


is Palindrome


In [ ]:
#Q3) Find factorial of a number using recursion
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print("Factorial:", factorial(5))


Factorial: 120


In [ ]:
#Q4) Print Fibonacci sequence up to n terms.
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=' ')
        a, b = b, a + b

fibonacci(10)


0 1 1 2 3 5 8 13 21 34 

In [ ]:
#Q5) Check if a number is prime.
num = 17
is_prime = True

if num <= 1:
    is_prime = False
else:
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

if is_prime:
    print("Prime")
else:
    print("Not Prime")


Prime


In [ ]:
#Q6)Count vowels and consonants in a string.
s = "Hello Disha"
vowels = "aeiouAEIOU"
v = c = 0

for char in s:
    if char.isalpha():
        if char in vowels:
            v += 1
        else:
            c += 1

print("Vowels:", v)
print("Consonants:", c)


Vowels: 4
Consonants: 6


In [ ]:
#Q7) Find the largest and smallest number in a list.
# Take input from user
user_input = input("Enter numbers separated by space: ")
lst = list(map(int, user_input.split()))

# Bubble Sort
for i in range(len(lst)):
    for j in range(len(lst) - 1):
        if lst[j] > lst[j + 1]:
            lst[j], lst[j + 1] = lst[j + 1], lst[j]

print("Sorted List:", lst)


Enter numbers separated by space: 78 7 5 57 89 19 10
Sorted List: [5, 7, 10, 19, 57, 78, 89]


In [ ]:
#Q8)Remove duplicates from a list.
original = [1, 2, 2, 3, 4, 4, 5]
unique = []

for item in original:
    if item not in unique:
        unique.append(item)

print("Without Duplicates:", unique)


Without Duplicates: [1, 2, 3, 4, 5]


In [ ]:
#Q9)Sort a list without using built-in sort.
# Take input from user
user_input = input("Enter numbers separated by space: ")
lst = list(map(int, user_input.split()))

# Bubble Sort
for i in range(len(lst)):
    for j in range(len(lst) - 1):
        if lst[j] > lst[j + 1]:
            lst[j], lst[j + 1] = lst[j + 1], lst[j]

print("Sorted List:", lst)



Enter numbers separated by space: 3 78 87 767 5687 
Sorted List: [3, 78, 87, 767, 5687]


In [ ]:
#Q10)Swap two numbers without using a third variable

#Swap two numbers without using a third variable.
a = 10
b = 20

a = a + b  # a becomes 30
b = a - b  # b becomes 10
a = a - b  # a becomes 20

print("a:", a)
print("b:", b)


a: 20
b: 10


In [47]:
#Q11)Implement a binary search.
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid  # Found
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1  # Not found

# Example
arr = [1, 3, 5, 7, 9, 11]
target = 7
result = binary_search(arr, target)

if result != -1:
    print(f"Element {target} found at index {result}")
else:
    print(f"Element {target} not found")




Element 7 found at index 3


In [ ]:
#Q12)Find the second largest number in a list.
lst = list(map(int, input("Enter numbers: ").split()))
lst = list(set(lst))  # Remove duplicates

lst.sort()
if len(lst) >= 2:
    print("Second largest number:", lst[-2])
else:
    print("Not enough elements")


Enter numbers: 8 7 0 6 87 4 88 
Second largest number: 87


In [ ]:
#Q13)Find the most frequent element in a list.
lst = list(map(int, input("Enter numbers: ").split()))
max_count = 0
most_freq = lst[0]

for num in lst:
    count = lst.count(num)
    if count > max_count:
        max_count = count
        most_freq = num

print("Most frequent element:", most_freq)


Enter numbers: 1 2 3 4 5 6 7 8 9 
Most frequent element: 1


In [1]:
#Q14)Merge two sorted lists.
list1 = [10, 34, 89, 73, 89, 99,]
list2 = [79, 87, 67, 52, 78, 66,19]
merged = sorted(list1 + list2)
print("Merged List:", merged)



Merged List: [10, 19, 34, 52, 66, 67, 73, 78, 79, 87, 89, 89, 99]


In [ ]:
#Q15)Find all pairs in a list whose sum is equal to a target.
nums = list(map(int, input("Enter numbers: ").split()))
target = int(input("Enter target sum: "))

for i in range(len(nums)):

    for j in range(i+1, len(nums)):

        if nums[i] + nums[j] == target:
            print(f"Pair: ({nums[i]}, {nums[j]})")


Enter numbers: 2 4 3 5 7 
Enter target sum: 9
Pair: (2, 7)
Pair: (4, 5)


In [ ]:
#Q16)Check if two strings are anagrams.
a = input("Enter first string: ")
b = input("Enter second string: ")

if sorted(a) == sorted(b):
    print("Strings are anagrams")
else:

    print("Not anagrams")


Enter first string: dog
Enter second string: cat
Not anagrams


In [56]:
#Q17)Flatten a nested list.
nested = [1, [2, [3, 4]], 5]
flattened = []

def flatten_list(lst):
    for item in lst:
        if isinstance(item, list):
            flatten_list(item)
        else:
            flattened.append(item)

flatten_list(nested)
print("Flattened List:", flattened)


Flattened List: [1, 2, 3, 4, 5]


In [75]:
#Q18)Read a file and count word occurrences
sentence = input("Enter a sentence: ")
words = sentence.split()
reversed_words = words[::-1]
print("Reversed sentence:", ' '.join(reversed_words))


Enter a sentence: Hello DIsha
Reversed sentence: DIsha Hello


In [74]:
#Q19)Reverse words in a sentence.
sentence = "I am learning Python"
reversed_sentence = ' '.join(sentence.split()[::-1])
print(reversed_sentence)



Python learning am I


In [73]:
#Q20)Check balanced parentheses using stack.
def is_balanced(expr):
    stack = []
    for char in expr:
        if char in "([{": stack.append(char)
        elif char in ")]}":
            if not stack or {')':'(', ']':'[', '}':'{'}[char] != stack.pop():
                return False
    return not stack

# Example
print(is_balanced("({[]})"))


True


In [72]:
#Q21)Find all permutations of a string.
from itertools import permutations

s = "abc"
perm = [''.join(p) for p in permutations(s)]
print(perm)



['abc', 'acb', 'bac', 'bca', 'cab', 'cba']


In [71]:
#Q22)Find the longest substring without repeating characters.
s = "abcabcbb"
start = max_len = 0
used = {}

for i, c in enumerate(s):
    if c in used and start <= used[c]:
        start = used[c] + 1
    else:
        max_len = max(max_len, i - start + 1)
    used[c] = i

print("Length:", max_len)


Length: 3


In [70]:
#Q23)Design a class to model a real-world system (e.g., ATM, Library).

class ATM:
    def __init__(self, balance=0):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
        else:
            print("Insufficient funds")

atm = ATM(1000)
atm.withdraw(200)
print("Balance:", atm.balance)


Balance: 800


In [69]:
#Q24)Use decorators to time a function’s execution.
import time

def timer(func):
    def wrapper():
        start = time.time()
        func()
        print("Time:", time.time() - start)
    return wrapper

@timer
def test():
    for _ in range(1000000): pass

test()



Time: 0.022386789321899414


In [68]:
#Q25)Implement a basic version of map/filter/reduce
#map
def my_map(func, lst):
    return [func(x) for x in lst]

# Example
result = my_map(lambda x: x * 2, [1, 2, 3])
print("Map:", result)

#filter
def my_filter(func, lst):
    return [x for x in lst if func(x)]

# Example
result = my_filter(lambda x: x % 2 == 0, [1, 2, 3, 4])
print("Filter:", result)

#reduce
def my_reduce(func, lst):
    result = lst[0]
    for x in lst[1:]:
        result = func(result, x)
    return result

# Example
result = my_reduce(lambda x, y: x + y, [1, 2, 3, 4])
print("Reduce:", result)

Map: [2, 4, 6]
Filter: [2, 4]
Reduce: 10


In [67]:
#Q26)Using NumPy, create a 3x3 matrix with values from 1 to 9.
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
#Q27)Replace all missing values (NaN) in a pandas DataFrame with the mean.
import pandas as pd
import numpy as np

# Example DataFrame
data = {'A': [1, 2, np.nan], 'B': [4, np.nan, 6]}
df = pd.DataFrame(data)

# Replace NaN with column mean
df.fillna(df.mean(), inplace=True)

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [65]:
#Q28)Group a DataFrame by a column and calculate the average.
import pandas as pd

# Sample DataFrame
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance'],
    'Salary': [30000, 32000, 40000, 42000, 50000]
}
df = pd.DataFrame(data)

# Group by 'Department' and calculate average salary
avg_salary = df.groupby('Department')['Salary'].mean()

print(avg_salary)


Department
Finance    50000.0
HR         31000.0
IT         41000.0
Name: Salary, dtype: float64


In [64]:
#Q29)Write a function to calculate RMSE.
import numpy as np

def rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred) ** 2))

#example
y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
print("RMSE:", rmse(y_true, y_pred))




RMSE: 0.5


In [63]:
#Q30)Perform normalization (MinMax and Z-score).
import numpy as np

data = [10, 20, 30, 40, 50]

# Min-Max Normalization
minmax = [(x - min(data)) / (max(data) - min(data)) for x in data]
print("MinMax:", minmax)

# Z-Score Normalization
mean = np.mean(data)
std = np.std(data)
zscore = [(x - mean) / std for x in data]
print("Z-Score:", zscore)


MinMax: [0.0, 0.25, 0.5, 0.75, 1.0]
Z-Score: [np.float64(-1.414213562373095), np.float64(-0.7071067811865475), np.float64(0.0), np.float64(0.7071067811865475), np.float64(1.414213562373095)]


In [62]:
#Q31)Split a dataset into training and test set without sklearn.
import random

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random.shuffle(data)

split = int(0.8 * len(data))
train = data[:split]
test = data[split:]

print("Train:", train)
print("Test:", test)



Train: [5, 4, 10, 2, 6, 8, 3, 1]
Test: [9, 7]


In [61]:
#Q32)Implement gradient descent for linear regression.
def gradient_descent(x, y, lr=0.01, epochs=1000):
    m = c = 0
    n = len(x)
    for _ in range(epochs):
        y_pred = [m*i + c for i in x]
        dm = (-2/n) * sum(x[i]*(y[i]-y_pred[i]) for i in range(n))
        dc = (-2/n) * sum(y[i]-y_pred[i] for i in range(n))
        m -= lr * dm
        c -= lr * dc
    return m, c

# Example
x = [1, 2, 3, 4, 5]
y = [2, 4, 5, 4, 5]
m, c = gradient_descent(x, y)
print(f"y = {m:.2f}x + {c:.2f}")


y = 0.62x + 2.14


In [60]:
#Q33)Write a custom function to calculate correlation coefficient.
def correlation(x, y):
    n = len(x)
    mean_x, mean_y = sum(x)/n, sum(y)/n
    num = sum((x[i] - mean_x) * (y[i] - mean_y) for i in range(n))
    den = (sum((x[i] - mean_x)**2 for i in range(n)) * sum((y[i] - mean_y)**2 for i in range(n))) ** 0.5
    return num / den

# Example
x = [1, 2, 3, 4]
y = [10, 20, 30, 40]
print("Correlation:", correlation(x, y))


Correlation: 1.0


In [59]:
#Q34)Filter rows in a DataFrame based on multiple conditions.
import pandas as pd

df = pd.DataFrame({
    'Age': [25, 30, 35, 40],
    'Salary': [40000, 50000, 60000, 70000]
})

filtered = df[(df['Age'] > 30) & (df['Salary'] > 50000)]
print(filtered)





   Age  Salary
2   35   60000
3   40   70000


In [58]:
#Q35)Write a Python function to calculate p-value from scratch ---mainly in datascience
import math

def normal_cdf(x):  # Standard normal CDF
    return (1 + math.erf(x / math.sqrt(2))) / 2

def calculate_p_value(z):
    return 2 * (1 - normal_cdf(abs(z)))  # Two-tailed

# Example
z = 1.96
print("P-Value:", calculate_p_value(z))

P-Value: 0.049995790296440745
